easy_admin:
    entities:
#        # List the entity class name you want to manage
      - App\Entity\Wine
      - App\Entity\Region
      - App\Entity\Trophy
      - App\Entity\Variety
#        - App\Entity\Category
#        - App\Entity\User
