monolog:
    handlers:
        main:
            type: fingers_crossed
            action_level: error
            handler: deduplicated
            excluded_http_codes: [404, 405]
            buffer_size: 50 # How many messages should be saved? Prevent memory leaks
        nested:
            type: stream
            path: "php://stderr"
            level: debug
        deduplicated:
            type: deduplication
            handler: symfony_mailer
        symfony_mailer:
            type: symfony_mailer
            from_email: 'error@terra-lusitana.com'
            to_email: 'contact@terra-lusitana.com'
            subject: 'An Error occured! %%message%%'
            level: debug
            formatter: monolog.formatter.html
            content_type: text/html
        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine"]
